export const RSS_FEEDS = [
  {
    portal: "G1",
    handle: "g1",
    category: "política",
    url: "https://nitter.net/g1/rss",
    logo: "https://www.google.com/s2/favicons?domain=g1.globo.com&sz=64",
  },
  {
    portal: "CNN Brasil",
    handle: "CNNBrasil",
    category: "política",
    url: "https://nitter.net/CNNBrasil/rss",
    logo: "https://www.google.com/s2/favicons?domain=cnnbrasil.com.br&sz=64",
  },
  {
    portal: "Valor Econômico",
    handle: "valoreconomico",
    category: "economia",
    url: "https://nitter.net/valoreconomico/rss",
    logo: "https://www.google.com/s2/favicons?domain=valor.globo.com&sz=64",
  },
  {
    portal: "Canaltech",
    handle: "canaltech",
    category: "tecnologia",
    url: "https://nitter.net/canaltech/rss",
    logo: "https://www.google.com/s2/favicons?domain=canaltech.com.br&sz=64",
  },
  {
    portal: "MacMagazine",
    handle: "MacMagazine",
    category: "tecnologia",
    url: "https://nitter.net/MacMagazine/rss",
    logo: "https://www.google.com/s2/favicons?domain=macmagazine.com.br&sz=64",
  },
  {
    portal: "Omelete",
    handle: "omelete",
    category: "cinema",
    url: "https://nitter.net/omelete/rss",
    logo: "https://www.google.com/s2/favicons?domain=omelete.com.br&sz=64",
  },
  {
    portal: "Rolling Stone Brasil",
    handle: "rollingstonebr",
    category: "música",
    url: "https://nitter.net/rollingstonebr/rss",
    logo: "https://www.google.com/s2/favicons?domain=rollingstone.com.br&sz=64",
  },
];